steps:
  # Step 1: Copy files to VM-1
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp --recurse ./* vm-1:/var/www/html/ --zone=me-central1-a

  # Step 2: Copy files to VM-2
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp --recurse ./* vm-2:/var/www/html/ --zone=me-central1-a
